// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmoyaeasftcdztdyvloo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtb3lhZWFzZnRjZHp0ZHl2bG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NDU1OTMsImV4cCI6MjA5MTIyMTU5M30.YM7ekaKAgEqAocug9t5XYXtvIl-ByhFjqYQXeR8r-Lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});